name: 📚 Epic
description: Crear un nuevo Epic para funcionalidades principales
title: "[EPIC] [Área de Negocio] - [Resultado]"
labels: ["epic", "priority-medium"]
assignees:
  - bautista-coll
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Creación de Epic
        Utiliza esta template para crear un Epic que represente una funcionalidad mayor o iniciativa de negocio.

  - type: input
    id: business_area
    attributes:
      label: 🏢 Área de Negocio
      description: ¿A qué área del producto o negocio pertenece este epic?
      placeholder: ej. Autenticación, E-commerce, Reportes
    validations:
      required: true

  - type: textarea
    id: business_goal
    attributes:
      label: 🎯 Objetivo de Negocio
      description: |
        **Problema:** ¿Qué problema de negocio estamos resolviendo?
        **Criterios de Éxito:** ¿Cómo sabremos que este epic fue exitoso?
      placeholder: |
        **Problema:** Los usuarios no pueden...
        **Criterios de Éxito:** 95% de usuarios pueden completar la acción en menos de 2 segundos
    validations:
      required: true

  - type: textarea
    id: user_goal
    attributes:
      label: 👥 Usuarios Objetivo
      description: ¿Quién se beneficiará de este epic?
      placeholder: Nuevos usuarios, usuarios existentes, administradores, etc.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Prioridad de Negocio
      description: ¿Qué tan crítico es este epic?
      options:
        - Crítica (Bloquea otros trabajos)
        - Alta (Importante para el roadmap)
        - Media (Planificado para este trimestre)
        - Baja (Futuras consideraciones)
    validations:
      required: true

  - type: textarea
    id: requirement
    attributes:
      label: 📋 Requisitos de Alto Nivel
      description: Lista los requisitos principales de este epic
      placeholder: |
        - [ ] Requisito 1
        - [ ] Requisito 2
        - [ ] Requisito 3
    validations:
      required: true

  - type: textarea
    id: dependencies_risks
    attributes:
      label: 🚧 Dependencias y Riesgos
      description: |
        **Dependencias:** ¿De qué depende este epic?
        **Riesgos:** ¿Qué podría salir mal?
      placeholder: |
        **Dependencias:**
        - API externa de pagos
        - Aprobación del equipo de seguridad

        **Riesgos:**
        - Complejidad técnica alta
        - Limitaciones de tiempo

  - type: input
    id: estimate_duration
    attributes:
      label: ⏱️ Duración Estimada
      description: ¿Cuánto tiempo tomará completar este epic?
      placeholder: ej. 3 semanas, 2 meses
    validations:
      required: true

  - type: textarea
    id: success_kpi
    attributes:
      label: 📈 Métricas de Éxito
      description: ¿Cómo mediremos el éxito de este epic?
      placeholder: |
        - 90% tasa de finalización de registro
        - <2 segundos tiempo de respuesta
        - Cero vulnerabilidades críticas
